/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Tigerar1 (https://sketchfab.com/allanromanreyes)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cp-30-clone-d6a3e96042dd48b08eee93a163ba9bfd
Title: CP-30 Clone
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";


export default function C3PO(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(`${basePath}/models/cp30-transformed.glb`);
  const { actions } = useAnimations(animations, group)

  const modelRef = useRef() // Reference for the model

  // Animate the model's position
  useFrame((state, delta) => {
    if (modelRef.current) {
      modelRef.current.position.y = -1.1 + Math.sin(state.clock.elapsedTime) * 0.15
    }
  })

  return (
    <group ref={group} {...props} dispose={null} rotation={[0.25, 0, 0]} scale={1.5} position={[0, 0, 0]}>
      <group ref={modelRef} name="Sketchfab_Scene"> {/* Attach modelRef here */}
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.shadowsmash_000_mat}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.shadowsmash_000_mat}
          skeleton={nodes.Object_10.skeleton}
        />
        <mesh
          name="trip_righthand_closed_mesh_000_mat_0"
          castShadow
          receiveShadow
          geometry={nodes.trip_righthand_closed_mesh_000_mat_0.geometry}
          material={materials.shadowsmash_000_mat}
        />
      </group>
    </group>
  )
}

useGLTF.preload(`${basePath}/models/cp30-transformed.glb`);
