/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [20.79KB] > /Users/bigdaddi/projects/3D/scifi_drone/scene-transformed.glb [446.71KB] (-2049%)
Author: badge (https://sketchfab.com/badge3dart)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/scifi-drone-e5efecf43ca74d2898a9053bd51f7f76
Title: SciFi Drone
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Drone(props) {
  const group = useRef()
  const modelRef = useRef()
  const { nodes, materials, animations } = useGLTF('/models/drone-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.01
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group ref={modelRef} name="Sketchfab_Scene"> 
        <group name="RootNode" scale={0.003}>
          <group name="DroneHead" rotation={[-Math.PI / 2, 1.571, 0]} scale={[226.969, 234.186, 234.186]}>
            <mesh name="DroneHead_M1Robot_0" geometry={nodes.DroneHead_M1Robot_0.geometry} material={materials.M1Robot} />
            <mesh name="DroneHead_M2Robot_0" geometry={nodes.DroneHead_M2Robot_0.geometry} material={materials.M2Robot} />
          </group>
        </group>
        <mesh name="DroneWeapon1_M2Robot_0" geometry={nodes.DroneWeapon1_M2Robot_0.geometry} material={materials.M2Robot} rotation={[-Math.PI / 2, 1.571, 0]} scale={0.787} />
        <mesh name="DroneWeapon1_M1Robot_0" geometry={nodes.DroneWeapon1_M1Robot_0.geometry} material={materials.M1Robot} rotation={[-Math.PI / 2, 1.571, 0]} scale={0.787} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/drone-transformed.glb')
