/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [14.92KB] > /Users/bigdaddi/projects/3D/r2-d2/scene-transformed.glb [56.93KB] (-282%)
Author: Tigerar1 (https://sketchfab.com/allanromanreyes)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/r2-d2-6f4e69a5a7b14fc782a076dbc4146386
Title: R2-D2
*/
"use client"
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

export function R2Model(props) {
  const { nodes, materials } = useGLTF(`${basePath}/models/r2-transformed.glb`);

  const modelRef = useRef()
  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.01
    }
  })


  return (
    <group {...props} dispose={null} ref={modelRef} scale={[1.8,1.8,1.8]}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.r2d2_head_mat} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.r2d2_mat} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.shadowsmash_mat} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(`${basePath}/models/r2-transformed.glb`);