/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Toymancer Studio (https://sketchfab.com/toymancer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizard-staff-873f596fb3cc44998cb75a3dce60181f
Title: Wizard Staff
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Staff(props) {
  const { nodes, materials } = useGLTF('/models/staff-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff3_Wizard_Staff3_0.geometry}
        material={materials.Wizard_Staff3}
        rotation={[0, 0, 0]} // Adjusted rotation for vertical alignment
        scale={.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wizard_Staff2_Wizard_Staff2_0.geometry}
        material={materials.Wizard_Staff2}
        rotation={[0, 0, 0]} // Adjusted rotation for vertical alignment
        scale={.04}
      />
    </group>
  )
}

useGLTF.preload('/models/staff-transformed.glb')
